# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MapTools' do
    pod 'BaiduMapKit' #百度地图SDK
    pod 'AMap3DMap' #高德地图SDK
    pod 'AMapSearch'
    pod 'AMapLocation'
end
